'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class contaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=contaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property tbl_mf_catalogo() As DbSet(Of tbl_mf_catalogo)
    Public Property tbl_mf_cierre_contable() As DbSet(Of tbl_mf_cierre_contable)
    Public Property tbl_mf_detalle_partida() As DbSet(Of tbl_mf_detalle_partida)
    Public Property tbl_mf_empresa() As DbSet(Of tbl_mf_empresa)
    Public Property tbl_mf_modeda() As DbSet(Of tbl_mf_modeda)
    Public Property tbl_mf_partida() As DbSet(Of tbl_mf_partida)
    Public Property tbl_mf_periodo_contable() As DbSet(Of tbl_mf_periodo_contable)

End Class
