'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_mf_extracto_bancario
    Public Property id_extracto As Integer
    Public Property exb_fecha As Date
    Public Property exb_documento As String
    Public Property exb_descripcion As String
    Public Property exb_debito As Double
    Public Property exb_credito As Double
    Public Property exb_saldo As Double

    Public Overridable Property tbl_mf_conciliacion As ICollection(Of tbl_mf_conciliacion) = New HashSet(Of tbl_mf_conciliacion)

End Class
