'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_mf_saldos
    Public Property id_saldos As Integer
    Public Property id_catalogo As String
    Public Property id_empresa As Integer
    Public Property id_periodo As Integer
    Public Property sld_saldo_inicial As Double
    Public Property sld_saldo_anterior As Double

    Public Overridable Property tbl_mf_catalogo As tbl_mf_catalogo
    Public Overridable Property tbl_mf_periodo_contable As tbl_mf_periodo_contable

End Class
