'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_detalle_move
    Public Property id_tipo_movimiento As Integer
    Public Property dtm_fecha As Date
    Public Property id_cuenta As Integer
    Public Property dtm_documento As String
    Public Property dtm_nodocumento As String

    Public Overridable Property tbl_mf_cuenta As tbl_mf_cuenta
    Public Overridable Property tbl_mf_tipo_movimiento As tbl_mf_tipo_movimiento

End Class
