'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_mf_tipo_doc
    Public Property id_tipo_doc As Integer
    Public Property tpd_descripcion As String
    Public Property tpd_de As Nullable(Of Integer)
    Public Property tpd_hasta As Integer
    Public Property id_estado As Integer
    Public Property id_cuenta As Integer

    Public Overridable Property tbl_mf_cuenta As tbl_mf_cuenta

End Class
