'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_mf_tipo_movimiento
    Public Property id_tipo_movimiento As Integer
    Public Property tpm_descripcion As String
    Public Property tpm_tipo_trans As String
    Public Property id_estado As Integer

    Public Overridable Property tbl_detalle_move As tbl_detalle_move

End Class
