'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_mf_conciliacion
    Public Property id_conciliacion As Integer
    Public Property id_empresa As String
    Public Property cnc_fecha_final As Date
    Public Property cnc_fecha_inicio As Date
    Public Property cnc_descripcion As String
    Public Property id_banco As Integer
    Public Property id_extracto As Integer

    Public Overridable Property tbl_mf_bancos As tbl_mf_bancos
    Public Overridable Property tbl_mf_detalle_conc As ICollection(Of tbl_mf_detalle_conc) = New HashSet(Of tbl_mf_detalle_conc)
    Public Overridable Property tbl_mf_extracto_bancario As tbl_mf_extracto_bancario

End Class
