'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_mf_catalogo
    Public Property id_catalogo As String
    Public Property ctl_descripcion As String
    Public Property ctl_id_padre As String
    Public Property ctl_nivel As Integer
    Public Property id_estado As Integer

    Public Overridable Property tbl_mf_detalle_partida As ICollection(Of tbl_mf_detalle_partida) = New HashSet(Of tbl_mf_detalle_partida)

End Class
