'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_mf_detalle_conc
    Public Property id_detalle_cnc As Integer
    Public Property id_conciliacion As Integer
    Public Property id_tipo_doc As Integer
    Public Property dtc_fecha As Date
    Public Property dtc_descripcion As String
    Public Property dtc_monto As Double
    Public Property id_estado As Integer

    Public Overridable Property tbl_mf_conciliacion As tbl_mf_conciliacion

End Class
