'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_mf_tipo_cuenta
    Public Property id_tipo_cuenta As Integer
    Public Property tpc_descripcion As Integer
    Public Property id_estado As Integer

    Public Overridable Property tbl_mf_cuenta As ICollection(Of tbl_mf_cuenta) = New HashSet(Of tbl_mf_cuenta)

End Class
