'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_mf_detalle_partida
    Public Property id_detalle As Integer
    Public Property id_empresa As Integer
    Public Property dtp_debe As Double
    Public Property dtp_haber As String
    Public Property id_partida As Integer
    Public Property id_moneda As Integer
    Public Property id_catalogo As String

    Public Overridable Property tbl_mf_catalogo As tbl_mf_catalogo
    Public Overridable Property tbl_mf_modeda As tbl_mf_modeda
    Public Overridable Property tbl_mf_partida As tbl_mf_partida

End Class
